### ISSUE TITLE
Socket problem (local IP set to <unknown>)

### ISSUE THREAD

**Issue by hs06** [T0RST3N/fhem-XiaomiSmartHome#12]
Hey everyone,

I have a (usually very stable) FHEM setup. I noticed that the Xiaomi gateway was in state "disconnected" for a while. Hrm. I saw that also the FHEM IP was `<unknown>`. It seems the original IP is retreived by opening a UDP socket to google DNS and taking the own IP from the socket. My guess: There was no internet at the time when FHEM (re-)started.

However, the module also did not recover afterwards (connecting with string `<unknown>` as local IP probably wont work..). I set the verbosity to 5 and got a `Creating socket: Invalid argument` error. 

Unfortunately, I am quite a perl illiterate. Although I would like to improve the code/stability, I don't feel apt to do it. I hope that the report helps.

Best
Hendrik

```
2018.02.17 17:53:29 4: WEB_87.123.113.56_54615 POST /fhem?detail=MiHome&dev.getMiHome=MiHome&cmd.getMiHome=get&arg.getMiHome=UpdateAll&val.getMiHome=&XHR=1&addLinks=1&fwcsrf=csrf_890042065113789&fw_id=2730; BUFLEN:0
2018.02.17 17:53:29 5: Cmd: >get MiHome UpdateAll<
2018.02.17 17:53:29 5: MiHome: updateAllReadings> Starting UpdateALLReadings
2018.02.17 17:53:29 1: MiHome: updateAllReadings> Gateway is Disconnected trying to reconnect to 192.168.1.126
2018.02.17 17:53:29 5: MiHome: connect> ConnectStart
2018.02.17 17:53:29 4: MiHome: connecting
Creating socket: Invalid argument

```

**Comment by T0RST3N** [comment]
i will look at that
greetings
torsten
