### ISSUE TITLE
FHEM crashes when second Xiaomi Gateway is plugged in

### ISSUE THREAD

**Issue by JohGub** [T0RST3N/fhem-XiaomiSmartHome#13]
Hi,
I've defined two gateways in FHEM. If only one gateway is power on, each of them works fine. As soon as both are plugged in, FHEM crashes. It does not matter which one is plugged in first. FHEM even crashes if only one gateway is defined.

The logfile says:
1: PERL WARNING: Use of uninitialized value in string ne at ./FHEM/71_XiaomiSmartHome.pm line 152.
1: PERL WARNING: Use of uninitialized value in concatenation (.) or string at ./FHEM/71_XiaomiSmartHome.pm line 154.
1: PERL WARNING: Use of uninitialized value $name in concatenation (.) or string at ./FHEM/71_XiaomiSmartHome.pm line 168.
Can't call method "incr_parse" on an undefined value at ./FHEM/71_XiaomiSmartHome.pm line 169.

Can anybody help ?
Regards
John

**Comment by T0RST3N** [comment]
Hello John,
yes i know, please define one GW in FHEM and then diconnect from power, define then the second one  with power connected. After that connect the first one to power.
it's a known problem, but at the moment I don't have time to solve it. i hope, to get to it, in the next few weeks.
greetings
Torsten

**Comment by Maik2016** [comment]
I have the same problem, even if I try it like you suggested.

The problem happens only with 2 standard gateways, I also have a camera with a gateway there is no problem but this can not be changed to talk directly to (no option to enable the modus)

**Comment by macmattes** [comment]
same here, i have to wait till the SID is available in the device, remove them, then added the second device, wait till the SID is available, then the first can be plugged in,and booth are working.
maybe it will help to add the SID at the end of the definition or as attribute as fix value?

**Comment by T0RST3N** [comment]
fix is coming. i have a another problem i am working on right now.
