### ISSUE TITLE
use of uninitialized variable

### ISSUE THREAD

**Issue by saschaludwig** [T0RST3N/fhem-XiaomiSmartHome#14]
Hi

Du benutzt hier "fhemIP", diese wird aber nirgends definiert. Weiter oben im Source wird FHEMIP benutzt. Eventuell sollte man das mal fixen :-)

https://github.com/T0RST3N/fhem-XiaomiSmartHome/blob/2065ea1e8f620fdec0bf5b886ca54b28278b2d83/FHEM/71_XiaomiSmartHome.pm#L732

**Comment by T0RST3N** [comment]
Hi Sascha,

ok, danke gucke ich mir an, bin eh gerade dran...

Grüße
