### ISSUE TITLE
Problems with Net::Ping using 71_XiaomiSmartHome.pm

### ISSUE THREAD

**Issue by Sequenzial** [T0RST3N/fhem-XiaomiSmartHome#18]
Hi,

Fhem services stops while starting Fhem Service.

Log says:
`2018.07.21 11:37:01 5: Loading /opt/fhem//FHEM/71_XiaomiSmartHome.pm
Can't locate object method "new" via package "Net::Ping" (perhaps you forgot to load "Net::Ping"?) at /opt/fhem//FHEM/71_XiaomiSmartHome.pm line 361.`

Net::Ping is installed and uptodate:
`hajo@SmartHomeVM:/opt/fhem/log$ sudo cpan install Net::Ping`
`Loading internal null logger. Install Log::Log4perl for logging messages
Reading '/home/hajo/.cpan/Metadata'
  Database was generated on Fri, 20 Jul 2018 13:54:31 GMT
CPAN: Module::CoreList loaded ok (v5.20180120)
Net::Ping is up to date (2.68).`

Fhem is also uptodate.
When I remove the XiaomiSmartHome devices in fhem.cfg Fhem runns perfect and stable.

I have today reinstalled Ubuntu (now 18.04 LTS - before 16.04 LTS) cleanly, 
but I always end in this error with Xiaomi. 
The problem exists since thursday 19th July 2018.

It worked quiet good for half a year before with about ~15 Xiaomi devices.
I added 6 more Switches to the base (what works fine on the Xiaomi App).
Is there a limitation on devices per base on the fhem module?  

Thanks in common!!!

Some more details:
--------------------

Working devices without the new ones:
`define XiaomiBase XiaomiSmartHome 192.168.1.170
attr XiaomiBase devStateIcon {Color_devStateIcon(ReadingsVal($name,"rgb","000000"))}
attr XiaomiBase group Controller/Bridge
attr XiaomiBase icon audio_volume_high
attr XiaomiBase room FlurEG,STATUS,•00-Server,•51-Xiaomi Mi SmartHome
attr XiaomiBase verbose 0`

those were created by autocreate half a year ago:
`define XMI_158d000105cebd XiaomiSmartHome_Device 158d000105cebd magnet XiaomiBase
attr XMI_158d000105cebd alias Kühlschranktür
attr XMI_158d000105cebd devStateIcon open:fts_door_open@red close:fts_door@green
attr XMI_158d000105cebd room Küche,•51-Xiaomi Mi SmartHome`

`define XMI_158d0001116b69 XiaomiSmartHome_Device 158d0001116b69 sensor_ht XiaomiBase
attr XMI_158d0001116b69 alias Temperatur in der Küche
attr XMI_158d0001116b69 room Küche,•51-Xiaomi Mi SmartHome
attr XMI_158d0001116b69 stateFormat temperature °C, humidity %`

`define XMI_158d00016d9a85 XiaomiSmartHome_Device 158d00016d9a85 weather.v1 XiaomiBase
attr XMI_158d00016d9a85 alias Temperatur im Kühlschrank
attr XMI_158d00016d9a85 room Küche,•51-Xiaomi Mi SmartHome
attr XMI_158d00016d9a85 stateFormat temperature °C, humidity %`

`define XMI_158d000149b71f XiaomiSmartHome_Device 158d000149b71f switch XiaomiBase
attr XMI_158d000149b71f alias BTN1
attr XMI_158d000149b71f room •51-Xiaomi Mi SmartHome`

`define XMI_158d0001dc44b8 XiaomiSmartHome_Device 158d0001dc44b8 switch XiaomiBase
attr XMI_158d0001dc44b8 alias BTN2 (Küche)
attr XMI_158d0001dc44b8 room Küche,•51-Xiaomi Mi SmartHome`

`define XMI_158d00016c3ad0 XiaomiSmartHome_Device 158d00016c3ad0 switch XiaomiBase
attr XMI_158d00016c3ad0 alias BTN3 (Markiesentaster stop)
attr XMI_158d00016c3ad0 room Terrasse,•51-Xiaomi Mi SmartHome`

`define XMI_158d0001231947 XiaomiSmartHome_Device 158d0001231947 motion XiaomiBase
attr XMI_158d0001231947 alias SC1 (FlurOG)
attr XMI_158d0001231947 devStateIcon motion:motion_detector@red off:motion_detector@green no_motion:motion_detector@green
attr XMI_158d0001231947 room FlurOG,•51-Xiaomi Mi SmartHome`

`define XMI_158d0001d8e678 XiaomiSmartHome_Device 158d0001d8e678 motion XiaomiBase
attr XMI_158d0001d8e678 alias SC2 (Küche)
attr XMI_158d0001d8e678 devStateIcon motion:motion_detector@red off:motion_detector@green no_motion:motion_detector@green
attr XMI_158d0001d8e678 room Küche,•51-Xiaomi Mi SmartHome`

`define XMI_158d0001ae92d0 XiaomiSmartHome_Device 158d0001ae92d0 motion XiaomiBase
attr XMI_158d0001ae92d0 alias SC3 (FlurEG)
attr XMI_158d0001ae92d0 devStateIcon motion:motion_detector@red off:motion_detector@green no_motion:motion_detector@green
attr XMI_158d0001ae92d0 room FlurEG,•51-Xiaomi Mi SmartHome`

`define XMI_158d00011889d9 XiaomiSmartHome_Device 158d00011889d9 switch XiaomiBase
attr XMI_158d00011889d9 room FlurEG,STATUS,•00-Server,•51-Xiaomi Mi SmartHome`

`define XMI_158d00011865a0 XiaomiSmartHome_Device 158d00011865a0 switch XiaomiBase
attr XMI_158d00011865a0 room FlurEG,STATUS,•00-Server,•51-Xiaomi Mi SmartHome`

`define XMI_158d000118657d XiaomiSmartHome_Device 158d000118657d switch XiaomiBase
attr XMI_158d000118657d room FlurEG,STATUS,•00-Server,•51-Xiaomi Mi SmartHome`

`define XMI_158d0001186582 XiaomiSmartHome_Device 158d0001186582 switch XiaomiBase
attr XMI_158d0001186582 room FlurEG,STATUS,•00-Server,•51-Xiaomi Mi SmartHome`

`define XMI_158d00010af880 XiaomiSmartHome_Device 158d00010af880 switch XiaomiBase
attr XMI_158d00010af880 room FlurEG,STATUS,•00-Server,•51-Xiaomi Mi SmartHome`

I thought autocreate would just add the 6 new switches.

**Comment by AndySilvia** [comment]
How was this issue solved? Got the same error after installing module as described in wiki....

**Comment by AndySilvia** [comment]
FYI: added "use Net::Ping;" at the begin of your module -> works....
