### ISSUE TITLE
Number format of rotate reading

### ISSUE THREAD

**Issue by fhempy** [T0RST3N/fhem-XiaomiSmartHome#20]
Hallo,
wäre es möglich das rotate Reading auch mit "." als Dezimaltrennzeichen anzubieten damit man es nicht als Nummer umformatieren muss?
Danke & Gruß
Dominik

**Comment by T0RST3N** [comment]
Hi,
kannst Du mir mal ein Verbose 5 log machen und dann ein Rotate auslösen.
Sorry das ich mich erst jetzt melde. Habe keine Nachricht bekommen das Du das Issue aufgemacht hast.
Grüße
Torsten
